### ISSUE TITLE
remove IERC20 and IERC165 dependencies on IERC1363

### ISSUE THREAD

**Issue by TheSnakeWitcher** [vittominacori/erc1363-payable-token#19]
Hi , I am currently trying to create a ERC1363 compatible token and I am facing an `Linearization of inheritance graph impossible` error, [these](https://github.com/ethereum/solidity/issues/13142) and [these](https://github.com/ethereum/solidity/issues/13136) issues are related to it. .
In my case I declare a `IERC1363` interface without `IERC20` and `IERC165` which seems to solve the error. I would like to know what do you think about removing those interfaces. Thanks in advanced.

**Comment by vittominacori** [comment]
Hello, `ERC20` and `ERC165` are part of the implementation as defined in the [EIP](https://eips.ethereum.org/EIPS/eip-1363), so it should not be removed.

Can you share the code that gives you that error to check?

In this [ERC1363](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol) contract, both `ERC20` and `ERC165` are extended also if their interfaces are defined in [IERC1363](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/IERC1363.sol#L15C1-L15C40) and I have no linearization error.

**Comment by TheSnakeWitcher** [comment]
Sorry, I miss understood the causes of the error, It is actually related to my use case which isn't general. I opened the issue because I thought that the `ERC1363` contract could not be used together with the rest of [openzeppelin ERC20 extensions](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC20/extensions), but it is not the case, my bad, thanks and nice work 👍🏿
