### ISSUE TITLE
Why use if statement rather than require?

### ISSUE THREAD

**Issue by chriscrutt** [vittominacori/erc1363-payable-token#5]
Hiya. I'm still learning about solidity but in [`ERC1363.sol`](https://github.com/vittominacori/erc1363-payable-token/blob/184a23c88caef92c74f88e9af5852771efc89634/contracts/token/ERC1363/ERC1363.sol) it looks like [`_checkOnTransferReceived`](https://github.com/vittominacori/erc1363-payable-token/blob/184a23c88caef92c74f88e9af5852771efc89634/contracts/token/ERC1363/ERC1363.sol#L112) and [`_checkOnApprovalReceived`](https://github.com/vittominacori/erc1363-payable-token/blob/184a23c88caef92c74f88e9af5852771efc89634/contracts/token/ERC1363/ERC1363.sol#L144) (and maybe other functions in other files) use
```solidity
if (!spender.isContract()) {
    revert("ERC1363: approve a non contract address");
}
```
I was curious as to why that was chosen over this
```solidity
require(spender.isContract(), "ERC1363: approve a non contract address");
```
Same with this
```solidity
if (reason.length == 0) {
    revert("ERC1363: approve a non ERC1363Spender implementer");
} else {
    /// @solidity memory-safe-assembly
    assembly {
        revert(add(32, reason), mload(reason))
    }
}
```
as opposed to this
```solidity
require(reason.length > 0, ERC1363: approve a non ERC1363Spender implementer) // or != 0
/// @solidity memory-safe-assembly
assembly {
    revert(add(32, reason), mload(reason))
}
```
And potentially a few other cases where you use if statements where require statements could be. Is it more gas efficient to do if statements? Or just for readability/contract flow you like if statements better.

**Comment by vittominacori** [comment]
As we are not using custom errors but only string messages, the gas cost is pretty simple.

We used that most for readability.

**Comment by chriscrutt** [comment]
okay just checking, thanks.
